In [1]:
import pandas as pd
import numpy as np

In [3]:
datas = pd.date_range('20200101', periods=6)

df = pd.DataFrame(np.random.randn(6, 4), index=datas, columns=['Var_A', 'Var_B', 'Var_C', 'Var_D'])
df

               Var_A     Var_B     Var_C     Var_D
2020-01-01  0.160844 -1.251668  0.857584 -0.523244
2020-01-02  0.155811 -1.679320  0.423349  0.170493
2020-01-03 -0.064646  0.448496  0.192517 -0.830129
2020-01-04 -0.767514  0.712006 -0.822652 -0.756952
2020-01-05  0.090524 -1.526092  0.833252  0.766960
2020-01-06 -1.347357  0.667235  0.836050 -0.364941

In [6]:
df.shape
df.dtypes

Var_A    float64
Var_B    float64
Var_C    float64
Var_D    float64
dtype: object

In [8]:
df2 = pd.DataFrame({'A': 1.,
   ...:                     'B': pd.Timestamp('20130102'),
   ...:                     'C': pd.Series(1, index=list(range(4)), dtype='float32'),
   ...:                     'D': np.array([3] * 4, dtype='int32'),
   ...:                     'E': pd.Categorical(["test", "train", "test", "train"]),
   ...:                     'F': 'Python'})
df2

     A          B    C  D      E       F
0  1.0 2013-01-02  1.0  3   test  Python
1  1.0 2013-01-02  1.0  3  train  Python
2  1.0 2013-01-02  1.0  3   test  Python
3  1.0 2013-01-02  1.0  3  train  Python

In [7]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [10]:
df2.describe()

         A    C    D
count  4.0  4.0  4.0
mean   1.0  1.0  3.0
std    0.0  0.0  0.0
min    1.0  1.0  3.0
25%    1.0  1.0  3.0
50%    1.0  1.0  3.0
75%    1.0  1.0  3.0
max    1.0  1.0  3.0

In [11]:
df1 = df.reindex(index=datas[0:4], columns=list(df.columns) + ['Var_E'])
df1

               Var_A     Var_B     Var_C     Var_D  Var_E
2020-01-01  0.160844 -1.251668  0.857584 -0.523244    NaN
2020-01-02  0.155811 -1.679320  0.423349  0.170493    NaN
2020-01-03 -0.064646  0.448496  0.192517 -0.830129    NaN
2020-01-04 -0.767514  0.712006 -0.822652 -0.756952    NaN

In [12]:
df1.loc[datas[0]:datas[1], 'Var_E'] = 77
df1

               Var_A     Var_B     Var_C     Var_D  Var_E
2020-01-01  0.160844 -1.251668  0.857584 -0.523244   77.0
2020-01-02  0.155811 -1.679320  0.423349  0.170493   77.0
2020-01-03 -0.064646  0.448496  0.192517 -0.830129    NaN
2020-01-04 -0.767514  0.712006 -0.822652 -0.756952    NaN

In [14]:
df1.describe()

          Var_A     Var_B     Var_C     Var_D  Var_E
count  4.000000  4.000000  4.000000  4.000000    2.0
mean  -0.128876 -0.442622  0.162699 -0.484958   77.0
std    0.438546  1.198782  0.712416  0.456145    0.0
min   -0.767514 -1.679320 -0.822652 -0.830129   77.0
25%   -0.240363 -1.358581 -0.061275 -0.775246   77.0
50%    0.045583 -0.401586  0.307933 -0.640098   77.0
75%    0.157069  0.514373  0.531907 -0.349810   77.0
max    0.160844  0.712006  0.857584  0.170493   77.0

In [16]:
datas = pd.date_range('20190101', periods = 60, freq="D")

df = pd.DataFrame(np.random.randn(60,5), index = datas, columns = list("ABCDE")) 
df.head()

                   A         B         C         D         E
2019-01-01  0.319713 -0.482784 -1.885738  0.445934 -1.674228
2019-01-02 -0.113595  0.821870  0.200004 -0.612892 -1.996960
2019-01-03 -0.356973 -0.267139 -0.526494  0.904138 -2.101981
2019-01-04 -1.302152 -0.392620 -0.665742 -0.873685  0.461767
2019-01-05 -0.414031  0.708035 -0.691791  1.112076  0.141765

In [17]:
df.shape

(60, 5)

In [20]:
df['F'] = df.A[df.A > 0]
df.head()

                   A         B         C         D         E         F
2019-01-01  0.319713 -0.482784 -1.885738  0.445934 -1.674228  0.319713
2019-01-02 -0.113595  0.821870  0.200004 -0.612892 -1.996960       NaN
2019-01-03 -0.356973 -0.267139 -0.526494  0.904138 -2.101981       NaN
2019-01-04 -1.302152 -0.392620 -0.665742 -0.873685  0.461767       NaN
2019-01-05 -0.414031  0.708035 -0.691791  1.112076  0.141765       NaN

In [22]:
df2 = df.copy()
df2.head()

                   A         B         C         D         E         F
2019-01-01  0.319713 -0.482784 -1.885738  0.445934 -1.674228  0.319713
2019-01-02 -0.113595  0.821870  0.200004 -0.612892 -1.996960       NaN
2019-01-03 -0.356973 -0.267139 -0.526494  0.904138 -2.101981       NaN
2019-01-04 -1.302152 -0.392620 -0.665742 -0.873685  0.461767       NaN
2019-01-05 -0.414031  0.708035 -0.691791  1.112076  0.141765       NaN

In [29]:
df3 = df.copy()

In [36]:
df3.dropna().shape

(33, 6)

In [39]:
df2.F.fillna(np.mean(df2.A)).head()

2019-01-01    0.319713
2019-01-02    0.080639
2019-01-03    0.080639
2019-01-04    0.080639
2019-01-05    0.080639
Freq: D, Name: F, dtype: float64

In [40]:
df4 = df.copy()

In [43]:
df4.fillna(value = 77777).head()

                   A         B         C         D         E             F
2019-01-01  0.319713 -0.482784 -1.885738  0.445934 -1.674228      0.319713
2019-01-02 -0.113595  0.821870  0.200004 -0.612892 -1.996960  77777.000000
2019-01-03 -0.356973 -0.267139 -0.526494  0.904138 -2.101981  77777.000000
2019-01-04 -1.302152 -0.392620 -0.665742 -0.873685  0.461767  77777.000000
2019-01-05 -0.414031  0.708035 -0.691791  1.112076  0.141765  77777.000000

In [45]:
df2 = pd.DataFrame({'A': 1.,
   ...:                     'B': pd.Timestamp('20130102'),
   ...:                     'C': pd.Series(1, index=list(range(4)), dtype='float32'),
   ...:                     'D': np.array([3] * 4, dtype='int32'),
   ...:                     'E': pd.Categorical(["test", "train", "test", "train"]),
   ...:                     'F': 'Python',
   ...:                     'G': [2,2,4,4],
   ...:                     'H': [np.nan,2,4,np.nan]  })
df2

     A          B    C  D      E       F  G    H
0  1.0 2013-01-02  1.0  3   test  Python  2  NaN
1  1.0 2013-01-02  1.0  3  train  Python  2  2.0
2  1.0 2013-01-02  1.0  3   test  Python  4  4.0
3  1.0 2013-01-02  1.0  3  train  Python  4  NaN

In [49]:
df2.nunique(axis = 1, dropna = True)

0    6
1    6
2    6
3    6
dtype: int64

In [53]:
df2.drop_duplicates(subset= 'G', keep= False)

Empty DataFrame
Columns: [A, B, C, D, E, F, G, H]
Index: []

In [54]:
df = pd.DataFrame({'Col1':['A','A','B', np.nan, 'D','C'], 'Col2':[2,1,9,8,7,4], 'Col3':[0,1,9,4,2,3]})
df

  Col1  Col2  Col3
0    A     2     0
1    A     1     1
2    B     9     9
3  NaN     8     4
4    D     7     2
5    C     4     3

In [58]:
df.sort_values(by= ['Col1','Col2'], ascending= False)

  Col1  Col2  Col3
4    D     7     2
5    C     4     3
2    B     9     9
0    A     2     0
1    A     1     1
3  NaN     8     4